import React, { useEffect, useRef, useState } from 'react';
import { VoiceInput } from './VoiceInput';
import { Disclosure, Flow, Icon, Spot } from './ui';
import { dateLabel, families, familyName, feelings, type Command, type LearningState, type Page } from './types';
export type { LearningState } from './types';
type Props = { state: LearningState; command: Command; view: Page; busy: boolean; start: (mode?: string, conceptId?: string) => void; aiEnabled: boolean; openConnection: () => void; voiceAvailable: boolean };
type Draft = { key: string; answer: string; explanation: string; inputMode: string; speechOnsetMs: number | null; processingMs: number; hidden: boolean; support: '' | 'teach' | 'hint'; error: string };
const draftFor = (key: string): Draft => ({ key, answer: '', explanation: '', inputMode: 'typing', speechOnsetMs: null, processingMs: 0, hidden: false, support: '', error: '' });

export function LearningView({ state, command, view, busy, start, aiEnabled, openConnection, voiceAvailable }: Props) {
  // This component stays mounted across all three pages. Drafts are memory-only;
  // typing is never written to an unencrypted browser storage fallback.
  const [draft, setDraft] = useState<Draft>(() => draftFor(''));
  const [mode, setMode] = useState('short'), [topic, setTopic] = useState('');
  const [family, setFamily] = useState<string | null>(null), [filter, setFilter] = useState('all');
  const input = useRef<HTMLTextAreaElement>(null), resultHeading = useRef<HTMLHeadingElement>(null);
  const s = state.session, item = s?.exercise;
  const key = s && item ? `${s.id}:${item.id}` : '';
  const d = draft.key === key ? draft : draftFor(key);
  const update = (patch: Partial<Draft>) => setDraft(previous => ({ ...(previous.key === key ? previous : draftFor(key)), ...patch }));
  const context = { sessionId: s?.id, exerciseId: item?.id };
  const prepared = useRef(''), focusResult = useRef(false);
  useEffect(() => {
    if (!key) { setDraft(draftFor('')); prepared.current = ''; }
    else if (draft.key !== key) setDraft(draftFor(key));
  }, [key]);
  useEffect(() => {
    if (view !== 'Practice' || !item || item.sequence || busy || prepared.current === key || s?.result) return;
    prepared.current = key;
    void command('learn:prepare', context).then(ok => { if (!ok && prepared.current === key) prepared.current = ''; });
  }, [key, view, busy]);
  useEffect(() => {
    if (s?.result && focusResult.current && view === 'Practice') { focusResult.current = false; resultHeading.current?.focus({ preventScroll: true }); }
  }, [s?.result?.id, view]);

  if (!state.profile) return <div className="onboarding"><div className="onboarding-intro"><span className="eyebrow">ON THE SPOT / FIRST THINGS FIRST</span><h1>Make room<br/>for <em>your mind.</em></h1><p className="lede">Learn an idea. Find the words.<br/>Work it out at your own pace.</p><div className="onboarding-symbol" aria-hidden="true"><span>o</span><span>t</span><span>s</span><i/></div><p className="micro">No countdowns. No streak to keep alive.</p></div><section className="onboarding-form"><span className="eyebrow">MAKE IT YOURS</span><h2>Where shall we start?</h2><ProfileForm profile={null} command={command} busy={busy}/></section></div>;

  if (view === 'Today') {
    const nextReview = state.progress.filter(c => c.learned && c.due).sort((a, b) => new Date(a.due!).getTime() - new Date(b.due!).getTime())[0];
    const activeCount = s?.count ?? (mode === 'short' ? 4 : 12);
    const chosenFamily = families.find(f => f.id === family);
    return <>
      <div className="page-top"><span className="eyebrow">01 / TODAY</span><time dateTime={new Date().toISOString().slice(0, 10)}>{new Date().toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' })}</time></div>
      <section className="practice-desk" aria-labelledby="today-title">
        <div className="desk-copy"><span className="section-label"><span className="status-dot online"/>{s ? 'SESSION IN PROGRESS' : 'A LITTLE DAILY PRACTICE'}</span><h1 id="today-title">{s ? <>Back to<br/><em>your spot.</em></> : <>Ready,<br/><em>{state.profile.name.trim().split(/\s+/)[0] || 'when you are'}?</em></>}</h1><p className="lede">{s ? `Exercise ${s.index + 1} of ${s.count}. Your place is kept.` : 'One idea. Your own words.\nA few different ways to think.'}</p>
          <fieldset className="session-size" disabled={busy || !!s}><legend>How much room have you got?</legend><div className="size-options">{[['short', 'A quick go', '4 exercises'], ['daily', 'A little longer', '12 exercises']].map(([id, label, detail]) => <label key={id} className={(s?.mode ?? mode) === id ? 'chosen' : ''}><input type="radio" name="session-size" value={id} checked={(s?.mode ?? mode) === id} onChange={() => setMode(id)}/><span><strong>{label}</strong><small>{detail}</small></span><span className="radio-mark" aria-hidden="true"/></label>)}</div></fieldset>
          <label className="field topic-field">Start with<select value={topic} disabled={busy || !!s} onChange={e => setTopic(e.target.value)}><option value="">My next useful idea</option>{state.progress.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label>
        </div>
        <div className="desk-spot"><div className="instrument-label"><span>YOUR NEXT SESSION</span><span>OTS / {s ? 'RESUME' : 'GO'}</span></div><Spot count={activeCount} current={s?.index ?? 0} label={s ? 'Continue session' : 'Start session'} disabled={busy} onClick={() => start(mode, topic)}/><p className="spot-note">No timer. Hints whenever you need them.</p>{s && <span className="micro">Your typed answer stays here while you explore.</span>}</div>
        <div className="family-strip" aria-label="What is in a session">{families.map((f, i) => <button type="button" key={f.id} aria-expanded={family === f.id} aria-controls="family-description" className={family === f.id ? 'active' : ''} onClick={() => setFamily(family === f.id ? null : f.id)}><span className="family-index">0{i + 1}</span><Icon name={f.symbol} size={23}/><span>{f.title}</span></button>)}</div>
        <div className="family-description" id="family-description" data-open={!!chosenFamily}><div><p>{chosenFamily ? <><strong>{chosenFamily.short}.</strong> {chosenFamily.detail} All four skills are included in each session.</> : <span aria-hidden="true">Learn, words, reasoning and focus.</span>}</p></div></div>
      </section>
      <div className="under-desk"><section className="review-note"><span className="index-symbol" aria-hidden="true"><Icon name="archive" size={23}/></span><div><span className="eyebrow">{state.dueCount ? `${state.dueCount} READY TO REVISIT` : 'FOR ANOTHER MOMENT'}</span><h3>{nextReview?.title ?? 'Your collection starts here.'}</h3><p className="micro">{nextReview?.due ? `Next review: ${dateLabel(nextReview.due, true)}` : 'Ideas you practise will return when it is time to revisit them.'}</p>{nextReview && state.dueCount > 0 && <button className="text-button" disabled={busy} onClick={() => start('short', nextReview.id)}>{s ? 'Continue current session' : 'Start with a review'}<Icon name="chevron" size={14}/></button>}</div></section><section className="focus-note"><span className="eyebrow">YOUR FOCUS</span><p>{state.profile.goal || 'Understand it. Say it your way.'}</p><span className="micro">A practice space, not a test of intelligence.</span></section></div>
      <Disclosure title={<><span className="small-spot"/> A fresh question, with ChatGPT</>} className="ai-disclosure" initial={!!state.draft}><p className="muted">Create a variation from reviewed material. Your interests, goal and language are included. You check the question before it joins your sessions.</p><button className="secondary" disabled={busy || !aiEnabled} onClick={() => void command('learn:generate', { conceptId: topic || 'estimate' })}>Prepare a question</button>{!aiEnabled && <button className="text-button" onClick={openConnection}>Connect ChatGPT</button>}{state.draft && <section className="draft-review"><span className="eyebrow">YOUR CALL</span><h3>Keep this question?</h3><p>{state.draft.lesson}</p><p className="draft-prompt">{state.draft.prompt}</p><div className="actions"><button className="primary" disabled={busy} onClick={() => void command('learn:reviewDraft', { draftId: state.draft!.id, accept: true })}>Keep for future sessions</button><button className="text-button" disabled={busy} onClick={() => void command('learn:reviewDraft', { draftId: state.draft!.id, accept: false })}>Discard</button></div></section>}</Disclosure>
    </>;
  }
  if (view === 'Progress') {
    const learned = state.progress.filter(c => c.learned).length;
    const entries = state.progress.filter(c => filter === 'all' || (filter === 'learned' ? c.learned : !!c.due && new Date(c.due).getTime() <= Date.now()));
    return <><div className="page-top"><span className="eyebrow">03 / PROGRESS</span><span className="micro">Your own record. No leaderboards.</span></div><div className="collection-heading"><h1>Your<br/><em>collection.</em></h1><div className="collection-count"><strong>{String(learned).padStart(2, '0')}</strong><span>of {state.progress.length} ideas<br/>introduced</span></div></div>
      <div className="filter-row" role="group" aria-label="Filter ideas">{[['all', 'All ideas'], ['learned', 'Introduced'], ['due', 'Due for review']].map(([id, label]) => <button className={filter === id ? 'selected' : ''} aria-pressed={filter === id} onClick={() => setFilter(id)} key={id}>{label}</button>)}</div>
      <section className="concept-ledger" aria-label="Your ideas">{!entries.length && <div className="empty-note"><Icon name="archive" size={28}/><h2>{filter === 'due' ? 'Nothing due right now.' : 'An open page.'}</h2><p>{filter === 'due' ? 'Your next review will appear here.' : 'Practise your first idea to start this collection.'}</p><button className="text-button" onClick={() => start('short')} disabled={busy}>{s ? 'Continue session' : 'Start a session'}</button></div>}{entries.map(c => <Disclosure key={c.id} className="concept-entry" title={<span className="concept-summary"><span className="concept-number">{String(state.progress.indexOf(c) + 1).padStart(2, '0')}</span><strong>{c.title}</strong><span className={`concept-state ${c.learned ? 'introduced' : ''}`}>{c.learned ? 'Introduced' : 'Teach first'}</span></span>}><p className="muted">{c.reason}</p>{c.due && <p className="micro">Review {dateLabel(c.due, true)}</p>}<button className="secondary" disabled={busy} onClick={() => start('short', c.id)}>{s ? 'Continue current session' : c.learned ? 'Revisit this idea' : 'Start with this idea'}<Icon name="play" size={14}/></button></Disclosure>)}</section>
      <Disclosure title="How your practice is changing"><p className="micro">Like-for-like tasks only. These results do not measure general intelligence or health.</p>{state.comparisons.map(c => <section className="comparison" key={c.family}><h3>{familyName(c.family)}</h3><p className="muted">{c.matchedTasks ? `${c.recentCorrect} successful in the last ${Math.min(c.matchedTasks, 5)} comparable tasks at level ${c.level + 1}.` : 'A few more attempts will give you something to compare.'}</p>{c.first && c.latest && <div className="matched-pair"><div><span className="eyebrow">FIRST / {dateLabel(c.first.at)}</span><p>{c.first.answer}</p><span className="micro">{Math.round(c.first.score * 100)}% on this task</span></div><div><span className="eyebrow">LATEST / {dateLabel(c.latest.at)}</span><p>{c.latest.answer}</p><span className="micro">{Math.round(c.latest.score * 100)}% on this task</span></div></div>}</section>)}</Disclosure>
      <Disclosure title={`Recent answers${state.attempts.length ? ` · ${state.attempts.length}` : ''}`}><p className="micro">Change a result that does not fit. Corrections update your review schedule.</p>{!state.attempts.length && <p className="muted">Your first answer will appear here after you check it.</p>}{state.attempts.slice().reverse().map(a => <article className="attempt" key={a.id}><div className="attempt-heading"><h3>{familyName(a.family)}</h3><span className="micro">{dateLabel(a.at)} · {a.disputed ? 'Disputed' : a.score === null ? 'Unscored' : `${Math.round(a.score * 100)}%`}</span></div><p className="saved-answer">{a.answer || 'Skipped / no answer'}</p><Disclosure title="Adjust this result"><div className="actions"><button className="secondary" disabled={busy} onClick={() => void command('learn:correct', { attemptId: a.id, score: 1 })}>My answer fits</button><button className="text-button" disabled={busy || a.disputed} onClick={() => void command('learn:correct', { attemptId: a.id, score: null })}>{a.disputed ? 'Result disputed' : 'Dispute result'}</button></div><label className="field">Your explanation<select value={a.explanation} disabled={busy} onChange={e => void command('learn:correct', { attemptId: a.id, score: a.score, explanation: e.target.value })}><option value="">No explanation selected</option>{feelings.map(x => <option key={x}>{x}</option>)}</select></label></Disclosure></article>)}</Disclosure>
    </>;
  }
  if (!s || !item) return <><div className="page-top"><span className="eyebrow">02 / PRACTICE</span><span className="micro">At your pace.</span></div><section className="session-end"><span className="completion-mark" aria-hidden="true"><Icon name={state.summary ? 'check' : 'play'} size={32}/></span><span className="eyebrow">{state.summary ? 'SESSION COMPLETE' : 'THE SPOT IS YOURS'}</span><h1>{state.summary ? <>That’s a<br/><em>good place to stop.</em></> : <>Room to<br/><em>think.</em></>}</h1>{state.summary ? <><p className="completion-facts">{state.summary.count} exercises · {state.summary.correct} successful of {state.summary.checked} checked · {state.summary.skipped} skipped</p><p className="muted">{state.summary.conversation}</p></> : <p className="muted">A mix of learning, words, reasoning and focus. Nothing is timed.</p>}<button className="primary" disabled={busy} onClick={() => start(mode, topic)}>{state.summary ? 'Another session' : 'Start session'}<Icon name="play" size={16}/></button></section></>;
  const blocked = busy || !!item.sequence && !d.hidden;
  return <>
    <div className="page-top"><span className="eyebrow">02 / PRACTICE</span><span className="micro">No timer. Take your time.</span></div>
    <section className="exercise-stage" aria-labelledby="exercise-title">
      <aside className="session-spine"><Spot count={s.count} current={s.index} compact/><ol className="session-path" aria-label="Session exercises">{Array.from({ length: s.count }, (_, i) => <li key={i} className={i < s.index ? 'done' : i === s.index ? 'current' : ''} aria-current={i === s.index ? 'step' : undefined}><span className="path-dot" aria-hidden="true">{i < s.index && <Icon name="check" size={10}/>}</span><span>{families[i % 4].short}</span><span className="sr-only">{i < s.index ? 'Completed' : i === s.index ? 'Current exercise' : 'Upcoming'}</span></li>)}</ol></aside>
      <div className="exercise-work"><Flow identity={`${key}:${s.result ? 'result' : 'answer'}`}><div className="exercise-label"><Icon name={item.family}/><span className="eyebrow">{familyName(item.family)}</span><span className="micro">{s.teaching ? 'A new idea' : 'Your turn'}</span></div><h2 id="exercise-title" className="exercise-prompt">{item.prompt}</h2>
        {s.teaching && <aside className="teaching-note"><span className="eyebrow">FIRST, THE IDEA</span><p>{item.lesson}</p></aside>}
        {item.sequence && !d.hidden && !s.result && <div className="sequence"><span className="eyebrow">TAKE A LOOK. THEN HIDE IT.</span><ol aria-label="Sequence to remember">{item.sequence.map((shape, i) => <li key={i}><span aria-hidden="true">{({ circle: '○', square: '□', triangle: '△', diamond: '◇', star: '☆', rectangle: '▭' } as Record<string, string>)[shape] || '·'}</span><small>{shape}</small></li>)}</ol><button className="secondary" disabled={busy} onClick={async () => { if (await command('learn:prepare', context)) { update({ hidden: true }); requestAnimationFrame(() => input.current?.focus({ preventScroll: true })); } }}>Hide sequence and answer</button></div>}
        {!s.result ? <form className="answer-form" onSubmit={async e => {
          e.preventDefault(); if (blocked) return;
          if (!d.answer.trim()) { update({ error: 'Write an answer, speak it, or choose Skip.' }); input.current?.focus(); return; }
          update({ error: '' }); focusResult.current = true;
          const ok = await command('learn:answer', { ...context, answer: d.answer, explanation: d.explanation, inputMode: d.inputMode, speechOnsetMs: d.speechOnsetMs, processingMs: d.processingMs });
          if (!ok) focusResult.current = false;
        }}><div className="answer-label"><label htmlFor="answer">Your answer</label><span className="micro">In your own words</span></div><textarea ref={input} id="answer" value={d.answer} onChange={e => update({ answer: e.target.value, error: '' })} maxLength={4000} disabled={blocked} aria-invalid={!!d.error} aria-describedby={d.error ? 'answer-error' : undefined} placeholder={item.sequence && !d.hidden ? 'Hide the sequence when you are ready.' : 'Start wherever you like…'} rows={4}/>{d.error && <p id="answer-error" className="inline-error" role="alert">{d.error}</p>}
          <VoiceInput prompt={item.prompt} disabled={blocked || !voiceAvailable} onTranscript={(text, onset, delay) => { update({ answer: text, inputMode: 'speech', speechOnsetMs: onset, processingMs: d.processingMs + delay, error: '' }); input.current?.focus(); }}/>
          <Disclosure title="Anything worth noting?" className="feeling-disclosure"><label className="field">How did this feel? (optional)<select value={d.explanation} disabled={busy} onChange={e => update({ explanation: e.target.value })}><option value="">No note</option>{feelings.map(x => <option key={x}>{x}</option>)}</select></label><p className="micro">An unclear question or something you never learned will stay unscored.</p></Disclosure>
          <div className="answer-actions"><button className="primary" type="submit" disabled={blocked}>Check answer<Icon name="check" size={17}/></button><button className="text-button" type="button" disabled={busy} onClick={async () => { focusResult.current = true; if (!await command('learn:answer', { ...context, answer: '', explanation: d.explanation, skip: true })) focusResult.current = false; }}>Skip this one</button></div>
        </form> : <section className="result" aria-label="Your result"><span className="eyebrow">{s.result.disputed ? 'RESULT DISPUTED' : s.result.status === 'skipped' ? 'SKIPPED, NOT FORGOTTEN' : s.result.score === null ? 'LET’S LOOK AT IT' : s.result.score === 1 ? 'ON THE SPOT' : 'SOMETHING TO REVISIT'}</span><h3 ref={resultHeading} tabIndex={-1} className="result-feedback">{s.result.feedback}</h3><div className="answer-reference"><div><span className="eyebrow">YOU SAID</span><p>{s.result.answer || 'No answer / skipped'}</p></div><div><span className="eyebrow">THE REFERENCE</span><p>{s.result.reference}</p></div></div><div className="answer-actions"><button className="primary" disabled={busy} onClick={() => void command('learn:next', context)}>{s.index + 1 === s.count ? 'Finish session' : 'Next exercise'}<Icon name="next" size={17}/></button></div>
          <Disclosure title="Does this result fit?"><div className="actions"><button className="secondary" disabled={busy} onClick={() => void command('learn:correct', { attemptId: s.result!.id, score: 1 })}>My answer fits</button><button className="text-button" disabled={busy || s.result.disputed} onClick={() => void command('learn:correct', { attemptId: s.result!.id, score: null })}>Dispute result</button></div>{['learn', 'words'].includes(item.family) && <><p className="micro">Optional AI feedback sends this question, reference and answer to OpenAI. It stays unscored until you correct or confirm it.</p><button className="secondary" disabled={busy || !aiEnabled} onClick={() => void command('learn:feedback', { attemptId: s.result!.id })}>Ask ChatGPT for feedback</button>{!aiEnabled && <button className="text-button" onClick={openConnection}>Connect ChatGPT</button>}</>}</Disclosure>
        </section>}
        {!s.result && <><div className="support-actions"><span className="micro">Need a hand?</span><button type="button" className="text-button" disabled={busy} aria-pressed={d.support === 'teach'} aria-controls="support-content" onClick={() => { const next = d.support === 'teach' ? '' : 'teach'; update({ support: next }); if (next) void command('learn:support', { ...context, kind: 'teach' }); }}>Teach me</button><button type="button" className="text-button" disabled={busy} aria-pressed={d.support === 'hint'} aria-controls="support-content" onClick={() => { const next = d.support === 'hint' ? '' : 'hint'; update({ support: next }); if (next) void command('learn:support', { ...context, kind: 'hint' }); }}>A small hint</button></div><div id="support-content" className="support-content" role="status">{d.support && <div className="teaching-note"><span className="eyebrow">{d.support === 'teach' ? 'THE EXPLANATION' : 'A NUDGE'}</span><p>{d.support === 'teach' ? item.lesson : item.hint}</p></div>}</div></>}
        <p className="source-note">{item.source}. This exercise runs offline.</p>
      </Flow></div>
    </section>
  </>;
}

export function ProfileForm({ profile, busy, command }: { profile: LearningState['profile']; busy: boolean; command: Command }) {
  const [saved, setSaved] = useState(false);
  return <form className="profile-form" onChange={() => setSaved(false)} onSubmit={async e => { e.preventDefault(); const data = new FormData(e.currentTarget); const ok = await command('learn:profile', Object.fromEntries(['name', 'interests', 'goal', 'language'].map(k => [k, String(data.get(k) ?? '')]))); setSaved(ok); }}><label className="field">What shall we call you?<input defaultValue={profile?.name} name="name" maxLength={80} autoComplete="given-name" placeholder="Your name"/></label><label className="field">What interests you?<input defaultValue={profile?.interests} name="interests" maxLength={300} placeholder="Films, languages, how things work…"/></label><label className="field">What would you like to practise?<input defaultValue={profile?.goal} name="goal" maxLength={300} placeholder="Finding words, explaining ideas…"/></label><label className="field">Preferred language<input name="language" maxLength={80} defaultValue={profile?.language ?? 'English'}/></label><p className="micro">Starter exercises are in English. Your language preference is used for optional AI feedback. You can leave the other fields blank.</p><button className="primary" disabled={busy} type="submit">{profile ? 'Save profile' : 'Make it mine'}<Icon name="check" size={17}/></button>{saved && <span className="save-note" role="status">Profile saved.</span>}</form>;
}

export function PracticeSettings({ state, command, busy }: { state: LearningState; command: Command; busy: boolean }) {
  return <><label className="field">Motion<select disabled={busy} value={state.settings.motion ?? 'liquid'} onChange={e => void command('learn:settings', { ...state.settings, motion: e.target.value })}><option value="liquid">Full · connected transitions</option><option value="gentle">Gentle · minimal movement</option></select></label><p className="micro">Your system’s reduced-motion preference always takes priority.</p><label className="field">Maximum new ideas in one session<select value={state.settings.newItems} disabled={busy} onChange={e => void command('learn:settings', { ...state.settings, newItems: Number(e.target.value) })}>{[1, 2, 3, 4].map(n => <option key={n} value={n}>{n}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" checked={state.settings.reviewsFirst} disabled={busy} onChange={e => void command('learn:settings', { ...state.settings, reviewsFirst: e.target.checked })}/><span>Put due reviews first</span></label><p className="micro">Unfamiliar ideas are taught first. Missing or unclear answers do not count as forgetting. Reasoning and focus difficulty follow your checked attempts.</p></>;
}
